Repository wastadtlander/Youtube-Comment-Translator, pull requests merged in 2023-11, with the labels that each got.

#6 Updated Readme
  README.md
Labels: documentation

#8 UI
  README.md
  data/languages.json
  html/popup.html
  js/content.js
  js/popup.js
  lib/bootstrap.bundle.min.js
  lib/bootstrap.min.css
  manifest.json
Labels: enhancement

#19 Migrate Extension to React and Typescript
  .gitignore
  README.md
  craco.config.js
  package-lock.json
  package.json
  public/favicon.ico
  public/index.html
  public/logo192.png
  public/manifest.json
  public/robots.txt
  src/App.css
  src/App.tsx
  src/chromeServices/DOMEvaluator.ts
  src/chromeServices/content.ts
  src/index.css
  src/index.tsx
  src/react-app-env.d.ts
  src/reportWebVitals.ts
  src/setupTests.ts
  src/types.ts
  tsconfig.json
Labels: enhancement

#23 Standardized translation tag
  manifest.json
  src/chromeServices/content.ts
Labels: bug, enhancement

#21 Big refactors
  README.md
  craco.config.js
  js/content.js
  lib/bootstrap.bundle.min.js
  lib/bootstrap.min.css
  manifest.json
  package-lock.json
  public/manifest.json
  src/App.tsx
  src/background/content.ts
  src/components/App/App.css
  src/components/App/App.tsx
  src/components/Popup/popup.html
  src/components/Popup/popup.js
  src/index.tsx
  src/services/DOMEvaluator.ts
Labels: enhancement
